html:
  - changed-files:
      - any-glob-to-any-file: "*.html"

css:
  - changed-files:
      - any-glob-to-any-file: "*.css"

github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

labeler-config:
  - changed-files:
      - any-glob-to-any-file: ".github/labeler.yml"
